BDEPEND=>=app-editors/emacs-23.1:*
DEFINED_PHASES=compile configure install postinst postrm prepare setup unpack
DESCRIPTION=A major mode for editing Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=elisp
KEYWORDS=~amd64
LICENSE=Apache-2.0
RDEPEND=>=app-editors/emacs-23.1:*
SLOT=0
SRC_URI=https://github.com/spotify/dockerfile-mode/archive/v1.3.tar.gz -> dockerfile-mode-1.3.tar.gz
_eclasses_=elisp-common	36f97076abd90f943a34f8bcd58b5bcc	elisp	023dd24ad9e6d5e62907e7007f548ca3
_md5_=8add6121dd9c6ade232f872a5ad5a981
