BDEPEND=>=app-editors/emacs-23.1:*
DEFINED_PHASES=compile configure install postinst postrm prepare setup unpack
DESCRIPTION=A major mode for editing Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=elisp
KEYWORDS=~amd64
LICENSE=Apache-2.0
RDEPEND=>=app-editors/emacs-23.1:*
SLOT=0
SRC_URI=https://github.com/spotify/dockerfile-mode/archive/v1.4.tar.gz -> dockerfile-mode-1.4.tar.gz
_eclasses_=elisp-common	cf4fd1b0835b9f3e638724840468064a	elisp	b165dc0288d12ab26e86f41c56f03914
_md5_=8add6121dd9c6ade232f872a5ad5a981
