BDEPEND=>=app-editors/emacs-23.1:*
DEFINED_PHASES=compile configure install postinst postrm prepare setup unpack
DESCRIPTION=A major mode for editing Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
KEYWORDS=~amd64
LICENSE=Apache-2.0
RDEPEND=>=app-editors/emacs-23.1:*
SLOT=0
SRC_URI=https://github.com/spotify/dockerfile-mode/archive/v1.3.tar.gz -> dockerfile-mode-1.3.tar.gz
_eclasses_=elisp	00840e1f4eb277c757dbfa5abf73c4c7	elisp-common	34cc2b6f6d8914019a353fe39cff43ce
_md5_=8add6121dd9c6ade232f872a5ad5a981
