BDEPEND=>=app-editors/emacs-24:*
DEFINED_PHASES=compile configure install postinst postrm prepare setup unpack
DESCRIPTION=A major mode for editing Dockerfiles
EAPI=8
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=elisp
KEYWORDS=~amd64
LICENSE=Apache-2.0
RDEPEND=>=app-editors/emacs-24:*
SLOT=0
SRC_URI=https://github.com/spotify/dockerfile-mode/archive/v1.5.tar.gz -> dockerfile-mode-1.5.tar.gz
_eclasses_=elisp-common	e7aaa047873789f549ea3df2f04b2145	elisp	c1c17e9c24d72d3bd58c611de8116fb6
_md5_=b98bfaa6e8468063ce1445b31af7183f
