BDEPEND=>=app-editors/emacs-23.1:*
DEFINED_PHASES=compile configure install postinst postrm prepare setup unpack
DESCRIPTION=A major mode for editing Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=elisp
KEYWORDS=~amd64
LICENSE=Apache-2.0
RDEPEND=>=app-editors/emacs-23.1:*
SLOT=0
SRC_URI=https://github.com/spotify/dockerfile-mode/archive/v1.4.tar.gz -> dockerfile-mode-1.4.tar.gz
_eclasses_=elisp-common	6bfea130fc0f2cbd4cbc23dc12992349	elisp	8d41193227fc27c56371b201ec7d861c
_md5_=8add6121dd9c6ade232f872a5ad5a981
