# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.1.1.9999
#hackport: flags: -dev

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

TEST_PN="${PN}-tests"
TEST_P="${TEST_PN}-${PV}"

DESCRIPTION="Lightweight package providing commonly useful parser combinators"
HOMEPAGE="https://github.com/mrkkrp/parser-combinators"
SRC_URI+=" https://hackage.haskell.org/package/${TEST_P}/${TEST_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="test"
RESTRICT="test"

RDEPEND=">=dev-lang/ghc-8.6.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-dev
}

src_test() {
	if use test; then
		cabal-register-inplace || die
		local pkg_db="${S}/dist/package.conf.inplace"

		local old_S="${S}"
		export S="${WORKDIR}/${TEST_P}"
		pushd "${S}" > /dev/null || die

		export CABAL_TEST_SUITE=yes
		export CABAL_USE_HADDOCK=''
		haskell-cabal_src_configure \
			--package-db="${pkg_db}" \
			--flag=-dev

		haskell-cabal_src_compile

		SKIP_REGISTER_INPLACE=yes haskell-cabal_src_test

		popd > /dev/null || die
		export S="${old_S}"
	fi
}
